docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Intro: intro.md
    - Reference:
        - "The Module Manager": module-manager.md
        - "The Module Class": module-class.md
        - "The Module Autoloader": module-autoloader.md
        - "Best Practices when Creating Modules": best-practices.md
site_name: zend-modulemanager
site_description: zend-modulemanager
repo_url: 'https://github.com/zendframework/zend-modulemanager'
copyright: 'Copyright (c) 2005-2017 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'

